### ISSUE TITLE
你好除了YOLOX-S 其他模型都报错，这是什么原因？谢谢

### ISSUE THREAD

**Issue by vc815** [hpc203/yolox-opencv-dnn#1]
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    net = yolox(args.model, p6=args.with_p6, confThreshold=args.score_thr)
  File "main.py", line 9, in __init__
    self.net = cv2.dnn.readNet(model)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\dnn\src\onnx\onnx_importer.cpp:78: error: (-5:Bad argument) Can't read ONNX file: yolox_m.onnx in function 'cv::dnn::dnn4_v20210608::ONNXImporter::ONNXImporter'

**Comment by hpc203** [comment]
我这边读取5种模型都能正常运行的，程序都是在本地测试ok之后上传到github的。

**Comment by vc815** [comment]
> 
> 
> 我这边读取5种模型都能正常运行的，程序都是在本地测试ok之后上传到github的。

那就很奇怪了。  执行的Python，YOLOX-S模型可以，逐个更换其他模型名称，这些模型都放在一起跟目录中。 其他模型都报错。。。。

**Comment by vc815** [comment]
> 
> 
> 我这边读取5种模型都能正常运行的，程序都是在本地测试ok之后上传到github的。

那就很奇怪了。  执行的Python，YOLOX-S模型可以，逐个更换其他模型名称，这些模型都放在一起跟目录中。 其他模型都报错。。。。
