### ISSUE TITLE
读取onnx模型失败

### ISSUE THREAD

**Issue by Dandelion111** [hpc203/yolox-opencv-dnn#7]
你好，请问我用你提供的onnx模型可以读取并得出结果，用官方代码训练的自己的数据集并转成onnx，却读取不了是为什么呢？

**Comment by Dandelion111** [comment]
![image](https://user-images.githubusercontent.com/48303408/138584755-2db051fb-0ac7-4241-930b-7e43ecefc8d8.png)
这是用python代码出现的错误提示

**Comment by EkilGitHub** [comment]
> ![image](https://user-images.githubusercontent.com/48303408/138584755-2db051fb-0ac7-4241-930b-7e43ecefc8d8.png) 这是用python代码出现的错误提示
你看，我也遇到相同的问题，请问怎么解决的呢？
